FROM rust:latest
LABEL Author=TommyLike<tommylikehu@gmail.com>

RUN apt update -y

RUN rustup target add x86_64-unknown-linux-gnu

WORKDIR /app

CMD ["cargo", "build", "--release",  "--bin", "resalloc-kubernetes","--target", "x86_64-unknown-linux-gnu"]